import random
import requests

WORD_LIST = [
    "python",
    "hangman",
    "challenge",
    "programming",
    "wizard",
    "keyboard",
    "function",
    "variable",
    "define",
    "answer",
    "compare",
    "radioactive",
    "hierarchy",
    "imagine",
    "extremity",
    "scenario",
    "manage",
    "extensive",
    "experience",
    "constant",
    "variable",
    "complete",
    "thought",
    "delirious",
    "tourniquet",
    "operation",
    "immediate",
    "motivation",
    "regular",
    "problem",
    "situation",
    "altitude",
    "considerable",
    "conscious",
    "unconscious",
    "tragedy",
    "general",
    "decompression",
    "fortunate",
    "summon",
    "strength",
    "cargo",
    "explosive",
    "passenger",
    "patient",
    "exygen",
    "device",
    "ordeal",
    "attendant",
    "consequence",
    "surround",
    "tradition",
    "nevertheless",
    "description",
    "suspected",
    "perpetrator",
    "similarities",
    "differences",
    "resemble",
    "participant",
    "identify",
    "identity",
    "witness",
    "software",
    "deparment",
    "convention",
    "virtual",
    "include",
    "database",
    "check",
    "force",
    "against",
    "convince",
    "consider",
    "predecessor",
    "remove",
    "emperor",
    "crowned",
    "revenge",
    "vengance",
    "transcript",
    "speaker",
    "vestments",
    "retrieve",
    "deposed",
    "rebellion",
    "stripped",
    "pontificate",
    "confirm",
    "successor",
    "deny",
    "uncontrollable",
    "manipulate",
    "subdue",
    "experiment",
    "torture",
    "apparent",
    "insatiable",
    "despicable",
    "fascinating",
    "journey",
    "through",
    "ingenuity",
    "controversy",
    "surrender",
    "air",
    "cultivate",
    "absence",
    "uppredictability",
    "victimized",
    "observing",
    "bestselling",
    "ruthless",
    "effortless",
    "fantasies",
    "compelling",
    "formlessness",
    "gratitude",
    "necessary",
    "attention",
    "conceal",
    "outshine",
    "reputation",
    "unattainable",
    "changing",
    "continuous",
    "dreaming",
    "desiring",
    "obvious",
    "allurement",
    "favrication",
    "embellished",
    "comfortable",
    "profitable",
    "conception",
    "interesting",
    "pretty",
    "cookie",
    "treat",
    "grass",
    "mail",
    "flower",
    "pillow",
    "house",
    "towering",
    "thinking",
    "sideline",
    "intelligent",
    "mobile",
    "start",
    "afraid",
    "mocking",
    "believe",
]


def get_random_word():
    try:
        while True:
            word = requests.get(
                "https://random-word-api.herokuapp.com/word", timeout=3
            ).json()[0]
            if word.isalpha() and 4 <= len(word) <= 10:
                return word
    except Exception:
        return 'python'
        # return random.choice(WORD_LIST)


def get_word_from_user():
    while True:
        word = input(
                "Enter your secret word for Hangman (letters only): "
                ).lower()
        if word.isalpha():
            print("\n" * 50)
            return word
        else:
            print("Please enter a word with only letters.")
